cache:
  go: true
  directories:
  - $HOME/.cache
  - $HOME/bin
  - $HOME/gopath/pkg/mod
language: go
go: 1.12
env:
- GO111MODULE=on

install: $HOME/bin/golangci-lint || curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $HOME/bin v1.16.0
script: script/test
before_cache: rm -f $HOME/.cache/go-build/log.txt

after_success: if [[ -z "$task" ]] ; then bash <(curl -s https://codecov.io/bash) ; fi
