// Code generated by "stringer -type=PacketKind -trimprefix=Packet"; DO NOT EDIT.

package tele_api

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PacketInvalid-0]
	_ = x[PacketConnect-1]
	_ = x[PacketState-2]
	_ = x[PacketTelemetry-3]
	_ = x[PacketCommand-4]
	_ = x[PacketCommandReply-5]
}

const _PacketKind_name = "InvalidStateTelemetryCommandCommandReply"

var _PacketKind_index = [...]uint8{0, 7, 12, 21, 28, 40}

func (i PacketKind) String() string {
	if i >= PacketKind(len(_PacketKind_index)-1) {
		return "PacketKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PacketKind_name[_PacketKind_index[i]:_PacketKind_index[i+1]]
}
