#!/bin/bash
set -eu
base="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
test_flag=(-race -timeout=11s)
: ${remote?"must set env remote"}

echo "- run tests" >&2
set -x
go test "${test_flag[@]}" ./... >/dev/null || go test -v "${test_flag[@]}" ./...
GOARCH=amd64 GOOS=linux script/build
rsync -a build/venderctl $remote:~/
ssh -t $remote time \~/venderctl -config=venderctl.hcl "$@"
